### ISSUE TITLE
Not able to create and copy Predix Machine Adapter for Pi

### ISSUE THREAD

**Issue by SwathiKadambala** [PredixDev/predix-machine-template-adapter#1]
When trying to run sh ./scripts/quickstart.sh -cc -i  kitti, script failed at this point, showing exception like below, can you help resolving this. 

Created Predix Machine container and updated the property files with UAA and Time Series info
###### ############################################### Build and setup the Predix Machine Adapter for Raspberry Pi

cp /Users/Swathi/Predix/predix-machine-template-adapter-pi/config/com.ge.predix.solsvc.workshop.adapter.config /Users/Swathi/Predix/predix-machine-template-adapter-pi/predix-scripts/bash/PredixMachine/configuration/machine
cp /Users/Swathi/Predix/predix-machine-template-adapter-pi/config/com.ge.predix.workshop.nodeconfig.json /Users/Swathi/Predix/predix-machine-template-adapter-pi/predix-scripts/bash/PredixMachine/configuration/machine
cp /Users/Swathi/Predix/predix-machine-template-adapter-pi/config/com.ge.dspmicro.hoover.spillway-0.config /Users/Swathi/Predix/predix-machine-template-adapter-pi/predix-scripts/bash/PredixMachine/configuration/machine
###### ############## Build and setup the adatper for Raspberry PI start

[ERROR] Failed to execute goal on project predix-machine-template-adapter-pi: Could not resolve dependencies for project com.ge.predix.solsvc:predix-machine-template-adapter-pi:bundle:1.0: The following artifacts could not be resolved: org.iot.raspberry:GrovePi-spec:jar:0.1.0-SNAPSHOT, org.iot.raspberry:GrovePi-dio:jar:0.1.0-SNAPSHOT, org.iot.raspberry:GrovePi-pi4j:jar:0.1.0-SNAPSHOT, org.iot.raspberry:Pi-spec:jar:0.1.0-SNAPSHOT, org.iot.raspberry:Pi-pi4j:jar:0.1.0-SNAPSHOT, org.iot.raspberry:Pi-dio:jar:0.1.0-SNAPSHOT: Could not find artifact org.iot.raspberry:GrovePi-spec:jar:0.1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by susheelvc** [comment]
Updated the POM to remove the unwanted dependencies. Please execute the command again.

**Comment by SwathiKadambala** [comment]
I tried executing the same command again today. Still i see same exception, what could be the reason. 

Created Predix Machine container and updated the property files with UAA and Time Series info
################################ Build and setup the Predix Machine Adapter for Raspberry Pi ################################
cp /Users/Swathi/Predix/predix-machine-template-adapter-pi/config/com.ge.predix.solsvc.workshop.adapter.config /Users/Swathi/Predix/predix-machine-template-adapter-pi/predix-scripts/bash/PredixMachine/configuration/machine
cp /Users/Swathi/MagikMinds/Predix/predix-machine-template-adapter-pi/config/com.ge.predix.workshop.nodeconfig.json /Users/Swathi/Predix/predix-machine-template-adapter-pi/predix-scripts/bash/PredixMachine/configuration/machine
cp /Users/Swathi/MagikMinds/Predix/predix-machine-template-adapter-pi/config/com.ge.dspmicro.hoover.spillway-0.config /Users/Swathi/Predix/predix-machine-template-adapter-pi/predix-scripts/bash/PredixMachine/configuration/machine
#################### Build and setup the adatper for Raspberry PI start ####################
[ERROR] Failed to execute goal on project predix-machine-template-adapter-pi: Could not resolve dependencies for project com.ge.predix.solsvc:predix-machine-template-adapter-pi:bundle:1.0: The following artifacts could not be resolved: org.iot.raspberry:GrovePi-spec:jar:0.1.0-SNAPSHOT, org.iot.raspberry:GrovePi-dio:jar:0.1.0-SNAPSHOT, org.iot.raspberry:GrovePi-pi4j:jar:0.1.0-SNAPSHOT, org.iot.raspberry:Pi-spec:jar:0.1.0-SNAPSHOT, org.iot.raspberry:Pi-pi4j:jar:0.1.0-SNAPSHOT, org.iot.raspberry:Pi-dio:jar:0.1.0-SNAPSHOT: Could not find artifact org.iot.raspberry:GrovePi-spec:jar:0.1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
